# rebuild wasm bundle & documentation with:
#
#   wasm-pack build --out-dir site/assets/wasm/r --target=web --no-default-features
#   cargo rustdoc
#   cp -r target/doc site/docs
#   cp site/templates/docs-redirect.html site/docs/index.html
#

[build]
rustdocflags = [
  "--default-theme",
  "ayu",
  "--html-in-header",
  "site/templates/rustdoc-header.html"
]
