name: Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pages:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: build rustdoc
        run: |
          cargo rustdoc
          rm -rf site/docs
          cp -r target/doc site/docs
          cp site/templates/docs-redirect.html site/docs/index.html

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm runtime
        run: |
          wasm-pack build --target web --out-dir docs/assets/wasm/r --no-default-features
          rm docs/assets/wasm/r/.gitignore

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          clean: false
          branch: gh-pages
          folder: site
